title: Simorq-Home
description: ""

author:
  name: Rahman Mohammadpour
  email: cimurq@pm.me

affiliation: Institute of Mathematics of Polish Academy of Sciences

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar

scholar:
  style: apa
  locale: en
  bibliography: "bibliography.bib"
  bibliography_list_tag: ul
  sort_by: year
  order: ascending
  bibliography_template: bib

include:
  - _static

# Update this section in your _config.yml
header_pages:
  - math/index.md          # Added this
  - math/finsidsat.md
  - math/publication.md
  - math/notes.md
  - math/slides.md
  - art/index.md           # Added this
  - art/work.md     # Added this

# Art Menu Data
art_pages:
  - title: "Collections"
    url: "/art/work"
  - title: "Posters"
    url: "/art/posters"
  - title: "Conference Doodling"
    url: "/art/doodling"

# URL Settings
permalink: /:categories/:title/
url: "https://si-morgh.github.io"
baseurl: ""  # Leave empty if your site is at si-morgh.github.io

minima:
  skin: classic